# Generated by Django 4.1.2 on 2022-11-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
