# Generated by Django 4.1.2 on 2022-11-27 11:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_remove_article_image_article_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
