# Generated by Django 4.1.2 on 2022-11-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_alter_article_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('RENT', 'Rent'), ('SALE', 'Sale')], default='RENT', max_length=30),
        ),
    ]
