# Generated by Django 4.1.2 on 2022-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_alter_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], default='rent', max_length=30),
        ),
    ]
