# Generated by Django 4.1.2 on 2022-11-03 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('Rec_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations_for', to=settings.AUTH_USER_MODEL)),
                ('Rec_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
